# ---------------------------------------------------------------------------
# RebuildRoadGeocodingService.py
# Created on: Thu Sep 18 2008 10:43:16 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Geocoding Tools.tbx")


# Local variables...
Centerline_Addresses_Zone__Rebuilt_ = "\\\\Missouri\\Desktop_GIS\\arcdata\\regional\\Centerline_Addresses_Zone"
Centerline_Addresses_Zone = "\\\\Missouri\\Desktop_GIS\\arcdata\\regional\\Centerline_Addresses_Zone"

# Process: Rebuild Address Locator...
gp.RebuildAddressLocator_geocoding(Centerline_Addresses_Zone)

